name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - "kubernetes/**"
      - ".github/workflows/docker-image-ci.yml"
  pull_request:
    paths:
      - "kubernetes/**"
      - ".github/workflows/docker-image-ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: setup docker actions
        env:
          TZ: "America/Denver"
        run: |
          echo "BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "VCS_REF=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: docker login
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS

      - name: Build image - nginx
        working-directory: ./kubernetes/nginx
        run: docker build -t lodotek/nginx:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - nginx
        if: github.event_name == 'push'
        run: docker push lodotek/nginx:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/nginx/7QCS0ho29O-wTHs3nIw5N2XZls8=

      - name: Build image - mysql
        working-directory: ./kubernetes/mysql
        run: docker build -t lodotek/mysql:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - mysql
        if: github.event_name == 'push'
        run: docker push lodotek/mysql:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/mysql/VdV3GfTNPegsi3iEgCzrSp7fcso=

      - name: Build image - postgres
        working-directory: ./kubernetes/postgres
        run: docker build -t lodotek/postgres:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - postgres
        if: github.event_name == 'push'
        run: docker push lodotek/postgres:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/postgres/buxVcrUNzGrKjvWm2_-mvfW5OHc=

      - name: Build image - mongodb
        working-directory: ./kubernetes/mongodb
        run: docker build -t lodotek/mongodb:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - mongodb
        if: github.event_name == 'push'
        run: docker push lodotek/mongodb:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/mongodb/UMosuG9BuAvvnGJ9gWcSzgBjC5k=

      - name: Build image - cassandra
        working-directory: ./kubernetes/cassandra
        run: docker build -t lodotek/cassandra:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - cassandra
        if: github.event_name == 'push'
        run: docker push lodotek/cassandra:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/cassandra/_v7rgss4iVQ4LkK4zscW7RKQGB8=

      - name: Build image - rabbitmq
        working-directory: ./kubernetes/rabbitmq
        run: docker build -t lodotek/rabbitmq:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - rabbitmq
        if: github.event_name == 'push'
        run: docker push lodotek/rabbitmq:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/rabbitmq/aN6TGvG8Z9g5SxT7PsSAS5ruys0=

      - name: Build image - jenkins
        working-directory: ./kubernetes/monitoring/jenkins
        run: docker build -t lodotek/jenkins:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - jenkins
        if: github.event_name == 'push'
        run: docker push lodotek/jenkins:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/jenkins/9IhdDnEDW1zwZc2v7l7DWfYTZ4E=

      - name: Build image - ab
        working-directory: ./kubernetes/monitoring/test/ab
        run: docker build -t lodotek/ab:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - ab
        if: github.event_name == 'push'
        run: docker push lodotek/ab:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/ab/Rd4WPZ1EPQWA2KTQwML6JyKoNgc=

      - name: Build image - postmannewman-quarkus
        working-directory: ./kubernetes/monitoring/test/postmannewman/quarkus
        run: docker build -t lodotek/postmannewman-quarkus:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - postmannewman-quarkus
        if: github.event_name == 'push'
        run: docker push lodotek/postmannewman-quarkus:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/postmannewman/JYNTOrYaF6nvNQVKCj1BGP1yBpM=

      - name: Build image - postmannewman-openliberty
        working-directory: ./kubernetes/monitoring/test/postmannewman/openliberty
        run: docker build -t lodotek/postmannewman-openliberty:latest
          --build-arg VCS_REF=${VCS_REF}
          --build-arg BUILD_DATE=${BUILD_DATE} .
      - name: Push Image - postmannewman-openliberty
        if: github.event_name == 'push'
        run: docker push lodotek/postmannewman-openliberty:latest
      - name: Update Microbadger
        if: github.event_name == 'push'
        run: curl -X POST -d {} https://hooks.microbadger.com/images/lodotek/postmannewman/JYNTOrYaF6nvNQVKCj1BGP1yBpM=
